name: adb_tool
description: The best ADB client for Android/Windows/Linux/macOS.
publish_to: "none"
version: 1.3.6+33
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  # localizations
  intl: ^0.17.0
  animations: ^2.0.2
  # desktop window stype
  flutter_acrylic: ^1.0.0
  # adb plugin can manager app
  app_manager:
    git: https://github.com/nightmare-space/app_manager
  # network
  dio: ^4.0.0
  # file drop
  desktop_drop: ^0.3.3
  file_selector: ^0.8.4+2
  # get app local dir
  path_provider: ^2.0.10
  # responsive ui
  responsive_framework: ^0.2.0
  flutter:
    sdk: flutter
  # terminal widget
  xterm:
    git:
      url: https://github.com/mengyanshou/xterm.dart
      ref: v3
  # local pty
  flutter_pty:
    git: https://github.com/TerminalStudio/flutter_pty
  # color select
  cyclop: ^0.5.2
  # some animations
  flutter_spinkit: "^4.1.2"
  # svg image
  flutter_svg: ^0.22.0
  # state manager...
  get: ^4.1.3
  # some foundation
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  # multicast on LAN
  multicast:
    git: https://github.com/nightmare-space/multicast
  
  file_manager_view:
    git: https://github.com/nightmare-space/file_manager_view.git
  # can receive mdns message
  multicast_dns: ^0.3.0
  # generate QR widget
  qr_flutter: ^4.0.0
  # scan qr code with camera
  qr_code_scanner: ^0.5.1
  path: ^1.8.0
  # launcher url
  url_launcher: ^6.0.18
  # show log
  logger_view:
    git: https://github.com/nightmare-space/logger_view
  # adb command util
  adbutil:
    git: https://github.com/nightmare-space/adbutil
  # file selector,but developed by nightmare
  file_selector_nightmare:
    git: https://github.com/nightmare-space/file_selector_meng
  # adb plugin can launcher app
  app_launcher:
    git: https://github.com/nightmare-space/app_launcher
  # foundation settings
  settings:
    git: https://github.com/nightmare-space/settings
  # adb plugin can view android device info and cpu/gpu status
  device_info:
    git: https://github.com/nightmare-space/device_info.git
  # can manage window on desktop
  window_manager: ^0.2.3
  
  flutter_markdown: ^0.6.10+2
  screenshot: ^1.2.3
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: MenloforPowerline
      fonts:
        - asset: assets/fonts/MenloforPowerline.ttf
  assets:
    - assets/
    - CHANGELOG.md

dependency_overrides:
  visibility_detector: ^0.3.3
  # logger_view:
  #   path: ../logger_view
  # global_repository:
  #   path: ../global_repository
  # # app_launcher:
  # #   path: ../app_launcher
  # # multicast:
  # #   path: ../multicast
  device_info:
    path: ../device_info
  # app_manager:
  #   path: ../app_manager
  adbutil:
    path: ../adbutil
  # xterm:
  #   path: /Users/nightmare/Desktop/nightmare-space/xterm.dart
  qr_code_scanner: ^1.0.0
  # file_selector_nightmare:
  #   path: ../file_selector_meng
flutter_intl:
  enabled: true
  localizely:
    project_id: 483edf0e-5f6c-489d-8b86-731bba09be1b
