name: adb_tool
description: 支持Android、macOS的adb工具，提供更方便的连接与设备操作.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.2.8+24
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  app_manager:
    git: https://github.com/nightmare-space/app_manager
  dio: ^4.0.0
  desktop_drop: ^0.2.0
  file_selector: ^0.8.2+1
  file_selector_linux: 0.0.2+1
  file_selector_macos: ^0.0.4+1
  file_selector_windows: ^0.0.2+1
  nativeshell:
    version: ^0.1.10
  animations: ^1.0.0+5
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.1
  flutter_screenutil: ^2.3.0
  flutter_spinkit: "^4.1.2"
  pseudo_terminal_utils:
    git: https://github.com/Termare/pseudo_terminal_utils
  # svg图像
  flutter_svg: ^0.22.0
  get: ^4.1.3
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  multicast:
    git: https://github.com/nightmare-space/multicast
  multicast_dns: ^0.3.0
  qr_flutter: ^3.1.0
  qr_code_scanner: ^0.5.1
  signale:
    git: https://github.com/Nightmare-MY/signale
  path: ^1.8.0
  termare_pty:
    git: https://github.com/Termare/termare_pty
  url_launcher: ^6.0.4
  adbutil:
    git: https://github.com/nightmare-space/adbutil
  termare_view:
    git: https://github.com/Termare/termare_view
  # 文件选择自实现方案
  file_selector_nightmare:
    git: https://github.com/nightmare-space/file_selector
  app_launcher:
    path: /Users/nightmare/Desktop/nightmare-space/app_launcher
  settings:
    path: /Users/nightmare/Desktop/Flutter_Package/settings
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: MenloforPowerline
      fonts:
        - asset: assets/fonts/MenloforPowerline.ttf
  assets:
    - assets/android/
    - assets/icon/
    - assets/

dependency_overrides:
# 下面代码注释掉，
  termare_view:
    path: /Users/nightmare/Desktop/termare-space/termare_view
  termare_pty:
    path: /Users/nightmare/Desktop/termare-space/termare_pty
  dart_pty:
    path: /Users/nightmare/Desktop/termare-space/dart_pty
  global_repository:
    path: /Users/nightmare/Desktop/nightmare-space/global_repository
  app_manager:
    path: /Users/nightmare/Desktop/nightmare-space/app_manager
  adbutil:
    path: /Users/nightmare/Desktop/nightmare-space/adbutil
    # path: C:\Users\Nightmare\Documents\termare-space\dart_pty
  signale:
    path: /Users/nightmare/Desktop/nightmare-space/signale
  app_launcher:
    path: /Users/nightmare/Desktop/nightmare-space/app_launcher
  file_selector_nightmare:
    path: /Users/nightmare/Desktop/nightmare-space/file_selector