name: adb_tool
description: 支持Android、macOS的adb工具，提供更方便的连接与设备操作.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.3.1+27
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  animations: ^2.0.2
  flutter_acrylic: ^1.0.0
  app_manager:
    git: https://github.com/nightmare-space/app_manager
  dio: ^4.0.0
  desktop_drop:
    git:
      url: https://github.com/mengyanshou/flutter-plugins
      path: packages/desktop_drop
  file_selector: ^0.8.2+1
  file_selector_linux: 0.0.2+1
  file_selector_macos: ^0.0.4+1
  file_selector_windows: ^0.0.2+1
  nativeshell:
    version: ^0.1.10
  flutter:
    sdk: flutter
  cyclop: ^0.5.2
  flutter_screenutil: ^2.3.0
  flutter_spinkit: "^4.1.2"
  pseudo_terminal_utils:
    git: https://github.com/Termare/pseudo_terminal_utils
  # svg图像
  flutter_svg: ^0.22.0
  get: ^4.1.3
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  multicast:
    git: https://github.com/nightmare-space/multicast
  multicast_dns: ^0.3.0
  qr_flutter: ^3.1.0
  qr_code_scanner: ^0.5.1
  path: ^1.8.0
  termare_pty:
    git: https://github.com/Termare/termare_pty
  url_launcher: ^6.0.18
  logger_view:
    git: https://github.com/nightmare-space/logger_view
  adbutil:
    git: https://github.com/nightmare-space/adbutil
  termare_view:
    git: https://github.com/Termare/termare_view
  # 文件选择自实现方案
  file_selector_nightmare:
    git: https://github.com/nightmare-space/file_selector_meng
  app_launcher:
    git: https://github.com/nightmare-space/app_launcher
  settings:
    git: https://github.com/nightmare-space/settings
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: MenloforPowerline
      fonts:
        - asset: assets/fonts/MenloforPowerline.ttf
  assets:
    - assets/android/
    - assets/
    - CHANGELOG.md

dependency_overrides:
#   global_repository:
#     path: /Users/nightmare/Desktop/nightmare-space/global_repository
  # app_manager:
  #   path: /Users/nightmare/Desktop/nightmare-space/app_manager
#   adbutil:
#   app_manager:
#     path: /Users/nightmare/Desktop/nightmare-space/app_manager
  adbutil:
    path: C:\Users\90626\Desktop\nightmare-space\adbutil
#     path: /Users/nightmare/Desktop/nightmare-space/adbutil
#   signale:
#     path: /Users/nightmare/Desktop/nightmare-space/signale
#   settings:
#     path: /Users/nightmare/Desktop/nightmare-space/settings
flutter_intl:
  enabled: true
  localizely:
    project_id: 483edf0e-5f6c-489d-8b86-731bba09be1b
